---

- name: Install Requirements
  sudo: yes
  pip: name=gunicorn state=present

- name: Create gunicorn Upstart Job
  sudo: yes
  template: src=foodlust.conf.j2 dest=/etc/init/foodlust.conf

- name: Start gunicorn Upstart Job
  sudo: yes
  service: name=foodlust state=restarted
